left_frame:
    username:   ""
    source:     "{{own}}"
    author:     ""
    categories: ""
    license:    "{{self|cc-zero}}"
    language:   "en"

right_frame:
    default_image_sort:   "file_name"

